import json
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "Aurora" / "ai_config.swift"

endpoint = (os.environ.get("SONIVO_AI_ENDPOINT") or "").rstrip("/")
token = os.environ.get("SONIVO_AI_TOKEN") or ""

if not token:
    # No secret provided in CI: keep the checked-in defaults so the app
    # silently falls back to the local ranking algorithm.
    print("SONIVO_AI_TOKEN is not set; keeping local-only AI config.")
    raise SystemExit(0)

if not endpoint:
    endpoint = "https://sonivo-ai.siarheismazhankoy.workers.dev"

content = (
    "import Foundation\n\n"
    "// Auto-generated by scripts/inject_ai_config.py during CI builds.\n"
    "enum SonivoAIConfig {\n"
    f"    static let endpoint = {json.dumps(endpoint)}\n"
    f"    static let token = {json.dumps(token)}\n"
    "}\n"
)
TARGET.write_text(content)
print("AI config injected for this build.")
