import SwiftUI
import CoreText

/// Offline brand-only derivative of Unbounded ExtraBold (SIL OFL 1.1).
/// Registration is performed once by the launch host, never by a rendering callback.
@MainActor enum SonivoLaunchTypography {
    private static var didPrepare = false
    private static var registeredName: String?
    static func prepare() -> String? {
        guard !didPrepare else { return registeredName }
        didPrepare = true
        guard let data = Data(base64Encoded: fontBase64, options: .ignoreUnknownCharacters),
              let provider = CGDataProvider(data: data as CFData),
              let font = CGFont(provider),
              let name = font.postScriptName else { return nil }
        guard CTFontManagerRegisterGraphicsFont(font, nil) else { return nil }
        registeredName = name as String
        return registeredName
    }
    // Brand glyphs only; the Russian subtitle remains native system typography.
    private static let fontBase64 = """
    AAEAAAAQAQAABAAAR0RFRgAYAAkAAAgQAAAAHEdQT1OPTpdlAAAILAAAAMhHU1VCGcsKdQAACPQAAAB8T1MvMmE6XiMAAAGIAAAA
    YFNUQVR5nmutAAAJcAAAACpjbWFwARkBHQAAAgwAAABMZ2FzcAAAABAAAAgIAAAACGdseWa05QBqAAACdAAAAd5oZWFkKH7LWQAA
    AQwAAAA2aGhlYQcdAU4AAAFEAAAAJGhtdHgUAgE8AAAB6AAAACRsb2NhAgsCaQAAAmAAAAAUbWF4cAAQAEIAAAFoAAAAIG5hbWV/
    bVuHAAAEVAAAA5Nwb3N0/58AMgAAB+gAAAAgcHJlcGgGjIUAAAJYAAAABwABAAAAAbN11tkMxF8PPPUAAwPoAAAAAN8/joQAAAAA
    5vBFSf///+8DOANFAAAABgACAAAAAAAAAAEAAAPj/wsAAANk///+1QM4AAEAAAAAAAAAAAAAAAAAAAAJAAEAAAAJAC8AAgARAAIA
    AQAAAAAAAAAAAAAAAAACAAEABAMoAyAABQAAAooCWAAAAEsCigJYAAABXgAyAVgAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAA
    TkFOAADAAFMAdgPj/wsAAATuAR4AAAABAAAAAAI9Au4AAAAgAAMDZABBA1kAJAFOACUBTgA0AU4AJQMlABkDIQAbAxT//wAAACYA
    AAACAAAAAwAAABQAAwABAAAAFAAEADgAAAAKAAgAAgACAFMAaQBvAHb//wAAAFMAaQBuAHb///+u/5n/l/+RAAEAAAAAAAAAAAAA
    uAH/hbAEjQAAAAAAAEMATgBdAGgAkgDEANkA7wABACT/7wM4Av8ALgAAdzMeAjMyNjU0JicnJiY1NDY2MzIWFhcjLgIjIgYVFBYX
    Fx4CFRQGBiMiJiYk7AQrSjJFTSxBhKKRXqhybqtlBewEJUQvPkkrOpFshTxgrXR3tGb2GicVICEXHQULDHVjUW04PnFLFiESHh4W
    HAUMCDNXQlB5Q0J3//8AJQAAASoDRQYmAAMAAAAGAAj/AAABADQAAAEZAkgABAAAUxc3ESM0c3LlAkgYGP24AP//ACUAAAEqA0UG
    JgADAAAABgAI/wAAAgAZAAAC+AJOAAUAGAAAUzMXESMRJTIWFhURIxE0JiMiBgYVJz4CGeUn5QGxVHQ/5js2JjgeRQ1PcgI97f6w
    AXPbQnlR/r4BITg8IDopJF18PwAAAgAb/+8DBQJOAA8AHwAARSImJjU0NjYzMhYWFRQGBicyNjY1NCYmIyIGBhUUFhYBkG+oXl6o
    cG+oXV2oby0/ISE/LS1AISFAEUyJWlyJS0uJXFqJTKggPSorPSAgPSorPSAAAAH//wAAAxQCPQAHAABlJxMzASEBMwGzTbvz/vj+
    +/74/W4BAc79wwI9AAEAJgJuASsDRQALAABTIiY1NDYzMhYVFAaoOkhIOjxHRwJuOjEyOjoyMToAAAAAAA0AogABAAAAAAEEAAYA
    AAABAAAAAAELAAkABgADAAEECQAAAK4ADwADAAEECQABACYAvQADAAEECQACAA4A4wADAAEECQADADQA8QADAAEECQAEACYAvQAD
    AAEECQAFAFYBJQADAAEECQAGACYAvQADAAEECQANASIBewADAAEECQAOADYCnQADAAEECQEEAAwC0wADAAEECQELABIC31dlaWdo
    dEV4dHJhQm9sZABDAG8AcAB5AHIAaQBnAGgAdAAgADIAMAAyADIAIABUAGgAZQAgAFUAbgBiAG8AdQBuAGQAZQBkACAAUAByAG8A
    agBlAGMAdAAgAEEAdQB0AGgAbwByAHMAIAAoAGgAdAB0AHAAcwA6AC8ALwBnAGkAdABoAHUAYgAuAGMAbwBtAC8AZwBvAG8AZwBs
    AGUAZgBvAG4AdABzAC8AdQBuAGIAbwB1AG4AZABlAGQAKQBTAG8AbgBpAHYAbwBMAGEAdQBuAGMAaABEAGkAcwBwAGwAYQB5AFIA
    ZQBnAHUAbABhAHIAUwBvAG4AaQB2AG8ATABhAHUAbgBjAGgARABpAHMAcABsAGEAeQAtADgAMAAwAC0AdgAxAFYAZQByAHMAaQBv
    AG4AIAAxAC4ANwAwADEAOwBnAGYAdABvAG8AbABzAFsAMAAuADkALgAyADgALgBkAGUAdgA1ACsAZwBlAGQAMgA5ADcAOQBkAF0A
    VABoAGkAcwAgAEYAbwBuAHQAIABTAG8AZgB0AHcAYQByAGUAIABpAHMAIABsAGkAYwBlAG4AcwBlAGQAIAB1AG4AZABlAHIAIAB0
    AGgAZQAgAFMASQBMACAATwBwAGUAbgAgAEYAbwBuAHQAIABMAGkAYwBlAG4AcwBlACwAIABWAGUAcgBzAGkAbwBuACAAMQAuADEA
    LgAgAFQAaABpAHMAIABsAGkAYwBlAG4AcwBlACAAaQBzACAAYQB2AGEAaQBsAGEAYgBsAGUAIAB3AGkAdABoACAAYQAgAEYAQQBR
    ACAAYQB0ADoAIABoAHQAdABwAHMAOgAvAC8AcwBjAHIAaQBwAHQAcwAuAHMAaQBsAC4AbwByAGcALwBPAEYATABoAHQAdABwAHMA
    OgAvAC8AcwBjAHIAaQBwAHQAcwAuAHMAaQBsAC4AbwByAGcALwBPAEYATABXAGUAaQBnAGgAdABFAHgAdAByAGEAQgBvAGwAZAAA
    AwAAAAAAAP+cADIAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAH//wAPAAEAAAAMAAAAAAAAAAIAAgABAAIAAQAEAAcAAQABAAAACgAq
    ADgAA0RGTFQAFGN5cmwAFGxhdG4AFAAEAAAAAP//AAEAAAABa2VybgAIAAAAAQAAAAEABAACAAgAAQAIAAIATAAEAAAAXABwAAUA
    BgAAAAD/+wAA//j/3AAAAAAAAAAA//sAAAAAAAD//QAA//n/4AAA//z/+v/7AAD/5gAA/9wAAAAA/+4AAAABAAYAAQACAAQABQAG
    AAcAAQABAAcAAwABAAAAAQACAAAABAABAAEABwAEAAMAAAADAAIAAQAFAAEAAAAKAFYAZAADREZMVAAUY3lybAAebGF0bgAiAAQA
    AAAA//8AAAAAAAAAAAAFQVpFIAAiQ1JUIAAiS0FaIAAiVEFUIAAiVFJLIAAiAAD//wABAAAAAWxvY2wACAAAAAEAAAABAAQAAQAA
    AAEACAABAAYAAgABAAEAAgABAAEACAABAAAAFAABAAAAHAACd2dodAEEAAAAAgABAAAAAAELAyAAAAAA
    """
}
